name: Lower test
on: push
jobs:
  hello-world:
    name: Lower test ${{ matrix.thing }}
    strategy:
      matrix:
        thing: [Ubuntu Xenial, Debian Buster]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        run: |
          read -ra arr <<< "${{ matrix.thing }}"
          echo "::set-env name=OS::$(tr '[:upper:]' '[:lower:]' <<< "${arr[0]}")"
          echo "::set-env name=RELEASE::$(tr '[:upper:]' '[:lower:]' <<< "${arr[1]}")"
          echo "OS = $OS"
          echo "RELEASE = $RELEASE"
      - name: Read variables
        run: |
          echo "OS = $OS"
          echo "RELEASE = $RELEASE"
